name: Add Label
on:
  workflow_run:
    workflows: [Node.js CI]
    types:
      - requested
  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  on_failure: 
    if: ${{ github.event.workflow_run.conclusion == 'failed' }}
    runs-on: ubuntu-latest
    steps: 
                - uses: actions/checkout@v2
                - uses: christianvuerings/add-labels@v1
                  with:
                    labels: invalid
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
